services:
  storage:
    image: postgres:latest

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: activityservice


    ports:
      - "5432:5432"

  react:
    image: react-client-demo:latest
    ports:
      - "80:3000"

  service:
    image: activity-service:latest
    ports:
      - "1025:8080"

    depends_on:
      - storage

    environment:
      BACKGROUND_WORKER_INTERVAL: 1m
      BACKGROUND_WORKER_PERIOD_DURATION: 10m
      DATABASE_HOST: storage
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      DATABASE_DB_NAME: activityservice
      APP_PORT: 8080